DOMAIN = "fitx"
ICON = "mdi:weight-lifter"
CONF_LOCATIONS = 'locations'
CONF_ID = 'id'
CONF_NUM_ID = 'num_id'
ATTR_ADDRESS = "address"
ATTR_STUDIO_NAME = "studioName"
ATTR_ID = CONF_ID
ATTR_URL = "url"
ATTR_NUM_ID = CONF_NUM_ID
DEFAULT_ENDPOINT = "https://mein.fitx.de/nox/public/v1/studios/{num_id}/utilization"
REQUEST_METHOD = "GET"
REQUEST_AUTH = None
REQUEST_HEADERS = {'x-tenant': 'fitx'}
REQUEST_PAYLOAD = None
REQUEST_VERIFY_SSL = True