DOMAIN = "fitx"
DEFAULT_NAME = "FitX Studio"
ATTR_ADDRESS = "address"
ATTR_STUDIO_NAME = "studioName"
ICON = "mdi:weight-lifter"
CONF_LOCATIONS = 'locations'
CONF_ID = 'id'
SENSOR_PREFIX = 'fitx_'
DEFAULT_ENDPOINT = "https://www.fitx.de/fitnessstudios/{id}"
REQUEST_METHOD = "GET"
REQUEST_AUTH = None
REQUEST_HEADERS = None
REQUEST_PAYLOAD = None
REQUEST_VERIFY_SSL = True
UNIT_OF_MEASUREMENT = "%"
SCAN_INTERVAL = 5